services:
  nginx:
    image: nginx:latest
    deploy:
      resources:
        limits:
          memory: 500M
    restart: always
    expose:
      - "80"
    ports:
      - 8200:80"
    volumes:
      - /root/marketplacefe/build:/usr/share/nginx/html:rw
      - ./default.conf:/etc/nginx/conf.d/default.conf:rw
